Repository ilPhil/amaca-travel, pull requests merged in 2022-06, with the labels that each got.

#11 commit api call
  pages/index.js
  utils/fetch.js
  yarn.lock
Labels: enhancement

#18 Commit add layout arrange elements
  components/CardItem/index.module.scss
  components/Cart/Cart.js
  components/Hero/style.module.scss
  components/Map.js
  package-lock.json
  pages/index.js
  styles/Home.module.css
  yarn.lock
Labels: enhancement

#21 Titles for each slide
  components/Hero/index.jsx
  components/Hero/style.module.scss
  components/PixelHero/index.jsx
  components/PixelHero/style.module.scss
  package-lock.json
  package.json
  pages/index.js
  yarn.lock
Labels: enhancement

#19 Commit add-footer
  components/Footer/index.js
  package-lock.json
  package.json
  pages/index.js
  styles/globals.css
  yarn.lock
Labels: enhancement

#27 Feature/14 improve map functionality
  components/Map.js
  next.config.js
  package-lock.json
  package.json
  pages/_document.js
  pages/index.js
  public/Map-Pin.svg
  styles/map.module.scss
  yarn.lock
Labels: enhancement

#30 Commit add feature card
  components/CardItem/CardItem.jsx
  components/CardItem/index.module.scss
  components/Footer/index.js
  utils/fetch.js
Labels: enhancement

#39 general/ responsive style review
  components/CardItem/CardItem.jsx
  components/Footer/index.js
  components/Header/index.jsx
  components/Header/style.module.scss
  pages/_document.jsx
  pages/activity/[id].jsx
  pages/index.js
  styles/globals.css
  styles/map.module.scss
  yarn.lock
Labels: enhancement

#43 header/respons
  components/CardItem/index.module.scss
  components/Footer/index.js
  components/Header/index.jsx
  components/Header/style.module.scss
  components/Hero/style.module.scss
  pages/activity/[id].js
  pages/activity/style.module.scss
  styles/globals.css
Labels: enhancement

#45 Fix/price id pages
  pages/activity/[id].js
  pages/index.js
Labels: bug

#48 Feature/41 add city page and logo
  components/CardItem/CardItem.jsx
  components/CardItem/index.module.scss
  components/Footer/index.js
  components/Header/index.jsx
  components/Header/style.module.scss
  components/Hero/index.jsx
  components/Map.js
  pages/_app.js
  pages/_document.jsx
  pages/activity/[id].js
  pages/activity/style.module.scss
  pages/api/hello.js
  pages/city/[id].js
  pages/city/style.module.scss
  public/amaca.ico
  public/amaca.png
  public/favicon.ico
  styles/globals.css
  styles/map.module.scss
  utils/fetch.js
Labels: enhancement

#51 added card item carousel and fixed some style
  .gitignore
  components/CardItem/CardItem.jsx
  components/CardItem/index.module.scss
  components/Header/index.jsx
  components/Hero/index.jsx
  components/Hero/style.module.scss
  components/Map.js
  package-lock.json
  package.json
  pages/activity/[id].js
  pages/activity/style.module.scss
  pages/city/[id].js
  pages/city/style.module.scss
  styles/map.module.scss
  yarn.lock
Labels: enhancement

#53 Completed Cart Logic
  pages/Cart.js
  pages/activity/[id].js
  store/provider.js
  yarn.lock
Labels: enhancement

#54 Feature/54 fix css
  components/CardItem/CardItem.jsx
  components/CardItem/index.module.scss
  components/Header/index.jsx
  components/Header/style.module.scss
  components/Hero/style.module.scss
  components/Map.js
  pages/Cart.js
  pages/_document.jsx
  pages/activity/[id].js
  pages/city/[id].js
  pages/city/style.module.scss
  public/amaca.png
  public/amaca400x400.png
  public/cart.png
  public/freccia-l.ico
  public/freccia-r.ico
  store/provider.js
  styles/cart.module.scss
  styles/map.module.scss
  yarn.lock
Labels: enhancement

#55 Update README.md
  README.md
Labels: documentation
